function [results] = enumerateTakeN5()

load phycfull;
load y2hdata;
x = nchoosek(y2hdata.idxIndProtNS,5);
%load enumerateY2HChoose5;
%x = enumerateY2HChoose5;
z5 = find(phycfull.pHRange==5);
z7 = find(phycfull.pHRange==7);

results = (phycfull.charge(z5,x(:,1)).*phycfull.charge(z5,x(:,2)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,2)))' ...
    + (phycfull.charge(z5,x(:,1)).*phycfull.charge(z5,x(:,3)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,3)))' ...
    + (phycfull.charge(z5,x(:,1)).*phycfull.charge(z5,x(:,4)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,4)))' ...
    + (phycfull.charge(z5,x(:,1)).*phycfull.charge(z5,x(:,5)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,5)))' ...
    + (phycfull.charge(z5,x(:,2)).*phycfull.charge(z5,x(:,3)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,3)))' ...
    + (phycfull.charge(z5,x(:,2)).*phycfull.charge(z5,x(:,4)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,4)))' ...
    + (phycfull.charge(z5,x(:,2)).*phycfull.charge(z5,x(:,5)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,5)))' ...
    + (phycfull.charge(z5,x(:,3)).*phycfull.charge(z5,x(:,4)))./(phycfull.seqLength(x(:,3)).*phycfull.seqLength(x(:,4)))' ...
    + (phycfull.charge(z5,x(:,3)).*phycfull.charge(z5,x(:,5)))./(phycfull.seqLength(x(:,3)).*phycfull.seqLength(x(:,5)))' ...
    + (phycfull.charge(z5,x(:,4)).*phycfull.charge(z5,x(:,5)))./(phycfull.seqLength(x(:,4)).*phycfull.seqLength(x(:,5)))' ...
    - (phycfull.charge(z7,x(:,1)).*phycfull.charge(z7,x(:,2)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,2)))' ...
    - (phycfull.charge(z7,x(:,1)).*phycfull.charge(z7,x(:,3)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,3)))' ...
    - (phycfull.charge(z7,x(:,1)).*phycfull.charge(z7,x(:,4)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,4)))' ...
    - (phycfull.charge(z7,x(:,1)).*phycfull.charge(z7,x(:,5)))./(phycfull.seqLength(x(:,1)).*phycfull.seqLength(x(:,5)))' ...
    - (phycfull.charge(z7,x(:,2)).*phycfull.charge(z7,x(:,3)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,3)))' ...
    - (phycfull.charge(z7,x(:,2)).*phycfull.charge(z7,x(:,4)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,4)))' ...
    - (phycfull.charge(z7,x(:,2)).*phycfull.charge(z7,x(:,5)))./(phycfull.seqLength(x(:,2)).*phycfull.seqLength(x(:,5)))' ...
    - (phycfull.charge(z7,x(:,3)).*phycfull.charge(z7,x(:,4)))./(phycfull.seqLength(x(:,3)).*phycfull.seqLength(x(:,4)))' ...
    - (phycfull.charge(z7,x(:,3)).*phycfull.charge(z7,x(:,5)))./(phycfull.seqLength(x(:,3)).*phycfull.seqLength(x(:,5)))' ...
    - (phycfull.charge(z7,x(:,4)).*phycfull.charge(z7,x(:,5)))./(phycfull.seqLength(x(:,4)).*phycfull.seqLength(x(:,5)))';

results = sortrows([x results'],4);
end